# Site settings
title: Catagraphic
email: adallens@catagraphic.com
description: > # this means to ignore newlines until "baseurl:"
 Poke around and see the cool stuff I've been making. Reach out on twitter if you want to chat.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: catagraphic
github_username:  adallensworth

# Build settings
markdown: kramdown
